language: go
go:
- "1.13.x"

before_install:
  - (cd /tmp && go get github.com/mattn/goveralls)

script:
- make test manager lint && git diff
- $GOPATH/bin/goveralls -service=travis-ci -coverprofile=cover.out

#todo: if we will have the scaffolds here as well then we need impl the testdata gen and an e2e test for that.